name: Release Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Set Up Node.js Environment
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3. Setup pnpm using the official action (specify exact version)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.8.2"  # Exact version to ensure installation
          run_install: false

      # 4. Install Dependencies and Global Packages
      - name: Install Dependencies and Global Packages
        run: |
          pnpm install --frozen-lockfile --strict-peer-dependencies
          pnpm add -g gulp prettier typescript

      # 5. Run Release Script
      - name: Run Release
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6. Push Changes Back to Repository
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main